param(
  [string]$CatalogPath = 'F:\MyProject\summary\wifi-manager-HarmonyOS\15-harmony-real-api-catalog.json',
  [string]$OutputPath = 'D:\HarmonyOS\WiFiEdgeManager\entry\src\main\ets\config\RealApiCatalog.ets'
)

$ErrorActionPreference = 'Stop'

$catalogFile = [System.IO.Path]::GetFullPath($CatalogPath)
$outputFile = [System.IO.Path]::GetFullPath($OutputPath)
$repositoryRoot = [System.IO.Path]::GetFullPath('D:\HarmonyOS\WiFiEdgeManager')
$expectedPrefix = $repositoryRoot.TrimEnd('\') + '\'

if (-not $outputFile.StartsWith($expectedPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
  throw "OutputPath must stay inside $repositoryRoot"
}
if (-not (Test-Path -LiteralPath $catalogFile -PathType Leaf)) {
  throw "Catalog not found: $catalogFile"
}

$catalog = Get-Content -LiteralPath $catalogFile -Raw -Encoding UTF8 | ConvertFrom-Json
if ($catalog.schemaVersion -ne '1.0') {
  throw "Unsupported catalog schemaVersion: $($catalog.schemaVersion)"
}

$seen = @{}
$endpoints = @($catalog.endpoints | Sort-Object -Property key)
$defaultGatewayUrl = [string]$catalog.clientPolicy.defaultGatewayUrl
$alertWebSocketPath = [string]$catalog.clientPolicy.alertWebSocketPath
if ($defaultGatewayUrl -notmatch '^https?://[^/\s]+(?::\d+)?$') {
  throw 'clientPolicy.defaultGatewayUrl must be an HTTP(S) origin'
}
if (-not $alertWebSocketPath.StartsWith('/')) {
  throw 'clientPolicy.alertWebSocketPath must start with /'
}
foreach ($endpoint in $endpoints) {
  $key = [string]$endpoint.key
  $path = [string]$endpoint.path
  $status = [string]$endpoint.status
  if ($key -notmatch '^[a-z][A-Za-z0-9.]+$') {
    throw "Invalid endpoint key: $key"
  }
  if ($seen.ContainsKey($key)) {
    throw "Duplicate endpoint key: $key"
  }
  if (-not $path.StartsWith('/')) {
    throw "Endpoint path must start with '/': $key"
  }
  if ($path.StartsWith('/internal/')) {
    throw "Mobile catalog cannot expose internal API: $key"
  }
  if ($status -notin @('CURRENT', 'PARTIAL', 'PREDICTED')) {
    throw "Invalid endpoint status for ${key}: $status"
  }
  $seen[$key] = $true
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('// Generated by tools/sync-real-api-catalog.ps1. Do not edit by hand.')
$lines.Add('')
$lines.Add("export function configuredDefaultGatewayUrl(): string { return '$defaultGatewayUrl' }")
$lines.Add("export function configuredAlertWebSocketPath(): string { return '$alertWebSocketPath' }")
$lines.Add('')
$lines.Add('export function realApiPath(key: string): string {')
$lines.Add('  switch (key) {')
foreach ($endpoint in $endpoints) {
  $key = ([string]$endpoint.key).Replace("'", "\'")
  $path = ([string]$endpoint.path).Replace("'", "\'")
  $lines.Add("    case '$key': return '$path'")
}
$lines.Add('    default: throw new Error(`Unknown Real API key: ${key}`)')
$lines.Add('  }')
$lines.Add('}')
$lines.Add('')
$lines.Add('export function resolveRealApiPath(key: string, names: string[], values: string[]): string {')
$lines.Add('  if (names.length !== values.length) throw new Error(''API path parameter count mismatch'')')
$lines.Add('  let path = realApiPath(key)')
$lines.Add('  for (let index = 0; index < names.length; index++) {')
$lines.Add('    path = path.replace(`{${names[index]}}`, encodeURIComponent(values[index]))')
$lines.Add('  }')
$lines.Add('  if (path.includes(''{'')) throw new Error(`Unresolved Real API path: ${key}`)')
$lines.Add('  return path')
$lines.Add('}')

$content = [string]::Join("`n", $lines) + "`n"
$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputFile, $content, $utf8)

$hash = (Get-FileHash -LiteralPath $catalogFile -Algorithm SHA256).Hash
Write-Output "REAL_API_CATALOG_SYNCED endpoints=$($endpoints.Count) catalogSha256=$hash output=$outputFile"
